/* Automatically generated by './build/bin/build-entry.js' */

import Breadcrumb from '../packages/breadcrumb/index.js'
import Dropdown from '../packages/dropdown/index.js'
import FormItemSelect from '../packages/form-item-select/index.js'
import Preview from '../packages/preview/index.js'
import Submenu from '../packages/submenu/index.js'
import Carousel from '../packages/carousel/index.js'
import FormItemBase from '../packages/form-item-base/index.js'
import Menu from '../packages/menu/index.js'
import Progress from '../packages/progress/index.js'
import Table from '../packages/table/index.js'
import Checkbox from '../packages/checkbox/index.js'
import CheckboxButton from '../packages/checkbox-button/index.js'
import CheckboxGroup from '../packages/checkbox-group/index.js'
import FormItemCheckbox from '../packages/form-item-checkbox/index.js'
import Msg from '../packages/msg/index.js'
import Radio from '../packages/radio/index.js'
import RadioButton from '../packages/radio-button/index.js'
import RadioGroup from '../packages/radio-group/index.js'
import Timeline from '../packages/timeline/index.js'
import Collapse from '../packages/collapse/index.js'
import FormItemInput from '../packages/form-item-input/index.js'
import Page from '../packages/page/index.js'
import Select from '../packages/select/index.js'
import Dialog from '../packages/dialog/index.js'
import FormItemRadio from '../packages/form-item-radio/index.js'
import Popover from '../packages/popover/index.js'
import Steps from '../packages/steps/index.js'
import Button from '../packages/button/index.js'
import Component from '../packages/component/index.js'
import Link from '../packages/link/index.js'
import Alert from '../packages/alert/index.js'
import Tooltip from '../packages/tooltip/index.js'
import RegionPicker from '../packages/region-picker/index.js'
import Scrollbar from '../packages/scrollbar/index.js'
import Row from '../packages/row/index.js'
import Col from '../packages/col/index.js'
import Input from '../packages/input/index.js'
import Autocomplete from '../packages/autocomplete/index.js'
import InputNumber from '../packages/input-number/index.js'
import Cascader from '../packages/cascader/index.js'
import CascaderPanel from '../packages/cascader-panel/index.js'
import Switch from '../packages/switch/index.js'
import Slider from '../packages/slider/index.js'
import DatePicker from '../packages/date-picker/index.js'
import Upload from '../packages/upload/index.js'
import Rate from '../packages/rate/index.js'
import ColorPicker from '../packages/color-picker/index.js'
import Transfer from '../packages/transfer/index.js'
import TimeSelect from '../packages/time-select/index.js'
import TimePicker from '../packages/time-picker/index.js'
import Form from '../packages/form/index.js'
import FormItem from '../packages/form-item/index.js'
import TableColumn from '../packages/table-column/index.js'
import Tag from '../packages/tag/index.js'
import Tree from '../packages/tree/index.js'
import Pagination from '../packages/pagination/index.js'
import Badge from '../packages/badge/index.js'
import DateRanges from '../packages/date-ranges/index.js'
import Loading from '../packages/loading/index.js'
import MenuItem from '../packages/menu-item/index.js'
import MenuItemGroup from '../packages/menu-item-group/index.js'
import Tabs from '../packages/tabs/index.js'
import TabPane from '../packages/tab-pane/index.js'
import BreadcrumbItem from '../packages/breadcrumb-item/index.js'
import PageHeader from '../packages/page-header/index.js'
import locale from 'element-up/src/locale'
import CollapseTransition from 'element-up/src/transitions/collapse-transition'

const components = [
  Breadcrumb,
  Dropdown,
  FormItemSelect,
  Preview,
  Submenu,
  Carousel,
  FormItemBase,
  Menu,
  Progress,
  Table,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  FormItemCheckbox,
  Radio,
  RadioButton,
  RadioGroup,
  Timeline,
  Collapse,
  FormItemInput,
  Select,
  Dialog,
  FormItemRadio,
  Popover,
  Steps,
  Button,
  Component,
  Link,
  Alert,
  Tooltip,
  RegionPicker,
  Scrollbar,
  Row,
  Col,
  Input,
  Autocomplete,
  InputNumber,
  Cascader,
  CascaderPanel,
  Switch,
  Slider,
  DatePicker,
  Upload,
  Rate,
  ColorPicker,
  Transfer,
  TimeSelect,
  TimePicker,
  Form,
  FormItem,
  TableColumn,
  Tag,
  Tree,
  Pagination,
  Badge,
  DateRanges,
  MenuItem,
  MenuItemGroup,
  Tabs,
  TabPane,
  BreadcrumbItem,
  PageHeader,
  CollapseTransition
]

const install = function (Vue, opts = {}) {
  locale.use(opts.locale)
  locale.i18n(opts.i18n)

  components.forEach(component => {
    Vue.component(component.name, component)
  })

  Vue.use(Loading.directive)

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  }

  Vue.prototype.$loading = Loading.service
  Vue.prototype.$msg = Msg
  Vue.prototype.$message = Msg.message
  Vue.prototype.$msgbox = Msg.msgbox
  Vue.prototype.$alert = Msg.alert
  Vue.prototype.$confirm = Msg.confirm
  Vue.prototype.$prompt = Msg.prompt
  Vue.prototype.$notify = Msg.notify
  Vue.prototype.$page = Page
}

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '0.7.4',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  Loading,
  Breadcrumb,
  Dropdown,
  FormItemSelect,
  Preview,
  Submenu,
  Carousel,
  FormItemBase,
  Menu,
  Progress,
  Table,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  FormItemCheckbox,
  Msg,
  Radio,
  RadioButton,
  RadioGroup,
  Timeline,
  Collapse,
  FormItemInput,
  Page,
  Select,
  Dialog,
  FormItemRadio,
  Popover,
  Steps,
  Button,
  Component,
  Link,
  Alert,
  Tooltip,
  RegionPicker,
  Scrollbar,
  Row,
  Col,
  Input,
  Autocomplete,
  InputNumber,
  Cascader,
  CascaderPanel,
  Switch,
  Slider,
  DatePicker,
  Upload,
  Rate,
  ColorPicker,
  Transfer,
  TimeSelect,
  TimePicker,
  Form,
  FormItem,
  TableColumn,
  Tag,
  Tree,
  Pagination,
  Badge,
  DateRanges,
  MenuItem,
  MenuItemGroup,
  Tabs,
  TabPane,
  BreadcrumbItem,
  PageHeader
}
